### ISSUE TITLE
Error while ng build

### ISSUE THREAD

**Issue by subu1979** [protokoul/angular-build-obfuscation#1]
studio@Subramanyam hello-world-app % ng build
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'main'.
studio@Subramanyam hello-world-app %

**Comment by protokoul** [comment]
Hi @subu1979

I created this repo to replicate the problem that I was facing with setting up obfuscation in the angular code, so the code is supposed to give an error related to the custom webpack configuration, but the error that you shared is not what I was expecting. Could you confirm whether you have set up the node modules correctly? It seems that the error might be due to version mismatch.

**Comment by subu1979** [comment]
Yes, I have set up Node modules properly. We have the Angular obfuscation based on the below article, which is working fine for us.

https://www.9lessons.info/2022/10/angular-remove-unused-css-obfu.html
